/**
 * Seed Prompts to Firestore
 * One-time script to initialize prompt library
 */

import { getFirestore, FieldValue } from 'firebase-admin/firestore';

const db = getFirestore();

// Seed prompts data (copied from src/data/newPrompts.ts)
const SEED_PROMPTS = [
  // ===== תכנון ותכניות עבודה =====
  {
    title: 'בניית תכנית עבודה כיתתית',
    description: 'יצירת תכנית שנתית או חודשית מאורגנת לכיתה בשניות - עושים סדר בבלאגן',
    category: 'תכנון ותכניות עבודה',
    subcategory: 'תכנית עבודה כיתתית',
    promptTemplate: `אני מורה ל{{מקצוע}} בכיתה {{שכבה}}.
אני צריך/ה לבנות תכנית עבודה {{סוג_תכנית}} לכיתה שלי.

פרטי הכיתה:
- מספר תלמידים: {{מספר_תלמידים}}
- מאפיינים מיוחדים: {{מאפיינים}}

נושאים עיקריים לתכנון:
{{נושאים}}

בבקשה צור לי תכנית עבודה מסודרת הכוללת:
1. פריסת הנושאים לאורך התקופה
2. יעדים לכל תקופה
3. אבני דרך והערכות
4. פעילויות מרכזיות מומלצות
5. זמנים מוערכים לכל נושא

התכנית צריכה להיות ריאליסטית וגמישה.`,
    fields: [
      { id: 'מקצוע', label: 'מקצוע', placeholder: 'מתמטיקה, עברית...', type: 'select', options: ['מתמטיקה', 'עברית', 'אנגלית', 'מדעים', 'היסטוריה', 'גאוגרפיה', 'אזרחות', 'תנ"ך', 'ספרות', 'אחר'], required: true },
      { id: 'שכבה', label: 'שכבה', placeholder: 'ד׳', type: 'select', options: ['א׳', 'ב׳', 'ג׳', 'ד׳', 'ה׳', 'ו׳', 'ז׳', 'ח׳', 'ט׳', 'י׳', 'י״א', 'י״ב'], required: true },
      { id: 'סוג_תכנית', label: 'סוג תכנית', placeholder: 'שנתית/חודשית', type: 'select', options: ['שנתית', 'סמסטריאלית', 'חודשית', 'רבעונית'], required: true },
      { id: 'מספר_תלמידים', label: 'מספר תלמידים', placeholder: '30', type: 'number', required: false },
      { id: 'מאפיינים', label: 'מאפייני הכיתה', placeholder: 'כיתה הטרוגנית, תלמידי שילוב...', type: 'text', required: false },
      { id: 'נושאים', label: 'נושאים עיקריים', placeholder: 'שברים, אחוזים, גאומטריה...', type: 'text', required: true }
    ],
    targetTools: ['ChatGPT', 'Claude', 'Gemini'],
    tips: 'ככל שתפרטו יותר על מאפייני הכיתה, התכנית תהיה מותאמת יותר לצרכים שלכם',
    createdBy: null,
    creatorName: 'מערכת',
    isAutoGenerated: true,
    status: 'active'
  },
  {
    title: 'כתיבת תכנית לימודית אישית (תל"א)',
    description: 'בניית מסלול למידה מותאם אישית לצרכים ולחוזקות של כל תלמיד ותלמידה',
    category: 'תכנון ותכניות עבודה',
    subcategory: 'תכנית לימודית אישית',
    promptTemplate: `אני מורה ל{{מקצוע}} וצריך/ה לבנות תכנית לימודית אישית (תל"א) עבור תלמיד/ה.

פרטי התלמיד/ה:
- שכבת גיל: {{שכבה}}
- חוזקות: {{חוזקות}}
- תחומים הדורשים חיזוק: {{תחומים_לחיזוק}}
- סגנון למידה מועדף: {{סגנון_למידה}}
- התאמות קיימות: {{התאמות}}

יעדים לתקופה:
{{יעדים}}

אנא בנה/י תכנית לימודית אישית הכוללת:
1. יעדים מדידים לטווח קצר וארוך
2. אסטרטגיות הוראה מותאמות
3. פעילויות והתאמות ספציפיות
4. דרכי הערכה מותאמות
5. נקודות מעקב והתקדמות
6. דרכים לשיתוף ההורים`,
    fields: [
      { id: 'מקצוע', label: 'מקצוע', placeholder: 'מתמטיקה', type: 'select', options: ['מתמטיקה', 'עברית', 'אנגלית', 'מדעים', 'היסטוריה', 'גאוגרפיה', 'אזרחות', 'תנ"ך', 'ספרות', 'כללי'], required: true },
      { id: 'שכבה', label: 'שכבה', placeholder: 'ה׳', type: 'select', options: ['א׳', 'ב׳', 'ג׳', 'ד׳', 'ה׳', 'ו׳', 'ז׳', 'ח׳', 'ט׳', 'י׳', 'י״א', 'י״ב'], required: true },
      { id: 'חוזקות', label: 'חוזקות התלמיד', placeholder: 'זיכרון חזותי טוב, יצירתיות...', type: 'text', required: true },
      { id: 'תחומים_לחיזוק', label: 'תחומים לחיזוק', placeholder: 'קריאה, ריכוז...', type: 'text', required: true },
      { id: 'סגנון_למידה', label: 'סגנון למידה', placeholder: 'חזותי, שמיעתי...', type: 'select', options: ['חזותי', 'שמיעתי', 'תנועתי', 'משולב'], required: false },
      { id: 'התאמות', label: 'התאמות קיימות', placeholder: 'הארכת זמן, הקראה...', type: 'text', required: false },
      { id: 'יעדים', label: 'יעדים לתקופה', placeholder: 'שיפור בקריאה, הגברת מוטיבציה...', type: 'text', required: true }
    ],
    targetTools: ['ChatGPT', 'Claude', 'Gemini'],
    tips: 'התכנית הזו מיועדת לתלמידים הזקוקים להתאמות מיוחדות. השתמשו בה בשיתוף יועץ/ת ופסיכולוג/ית בית הספר שלכם',
    createdBy: null,
    creatorName: 'מערכת',
    isAutoGenerated: true,
    status: 'active'
  },

  // ===== יצירת מבחנים =====
  {
    title: 'מחולל שאלות לבחינה',
    description: 'נתקעתם בלי רעיונות? מחולל שאלות בכל נושא שתבחרו לבחנים ומבחנים',
    category: 'יצירת מבחנים',
    subcategory: 'מבחן פתוח',
    promptTemplate: `אני מורה ל{{מקצוע}} בכיתה {{שכבה}} וצריך/ה רעיונות לשאלות בחינה.

נושא הבחינה: {{נושא}}

פרטים נוספים על החומר הנלמד:
{{פרטים}}

אנא צור {{מספר_שאלות}} שאלות מגוונות הכוללות:
1. שאלות ידע והבנה בסיסיות
2. שאלות יישום
3. שאלות חשיבה מסדר גבוה (ניתוח, הערכה, יצירה)

לכל שאלה ציין:
- רמת קושי (קל/בינוני/מאתגר)
- ניקוד מומלץ
- תשובה לדוגמה או כיווני תשובה`,
    fields: [
      { id: 'מקצוע', label: 'מקצוע', placeholder: 'מתמטיקה', type: 'select', options: ['מתמטיקה', 'עברית', 'אנגלית', 'מדעים', 'היסטוריה', 'גאוגרפיה', 'אזרחות', 'תנ"ך', 'ספרות', 'אחר'], required: true },
      { id: 'שכבה', label: 'שכבה', placeholder: 'ו׳', type: 'select', options: ['א׳', 'ב׳', 'ג׳', 'ד׳', 'ה׳', 'ו׳', 'ז׳', 'ח׳', 'ט׳', 'י׳', 'י״א', 'י״ב'], required: true },
      { id: 'נושא', label: 'נושא הבחינה', placeholder: 'מלחמת העצמאות', type: 'text', required: true },
      { id: 'פרטים', label: 'פרטים על החומר', placeholder: 'למדנו על הרקע, הכרזת העצמאות, המלחמה...', type: 'text', required: false },
      { id: 'מספר_שאלות', label: 'מספר שאלות', placeholder: '10', type: 'select', options: ['5', '10', '15', '20'], required: true }
    ],
    targetTools: ['ChatGPT', 'Claude', 'Gemini'],
    tips: 'פרטו כמה שיותר על החומר שנלמד כדי לקבל שאלות רלוונטיות יותר לצרכים שלכם',
    createdBy: null,
    creatorName: 'מערכת',
    isAutoGenerated: true,
    status: 'active'
  },
  {
    title: 'דף עבודה להדפסה',
    description: 'יצירת דף עבודה מותאם אישית בכל מקצוע וכל נושא - גמיש ומקיף',
    category: 'דפי עבודה',
    subcategory: 'דף עבודה להדפסה',
    promptTemplate: `אני מורה ל{{מקצוע}} בכיתה {{שכבה}} וצריך/ה דף עבודה להדפסה.

נושא: {{נושא}}
רמת קושי: {{רמת_קושי}}
{{פרטים}}

אנא צור דף עבודה הכולל:
1. כותרת ברורה ומעוצבת עם הנושא
2. {{מספר_תרגילים}} תרגילים/שאלות מגוונים
3. הוראות ברורות לכל חלק
4. מקום מסודר לתשובות התלמידים
5. תרגיל בונוס/אתגר בסוף (אופציונלי)

הדף צריך להיות:
- מותאם לרמת כיתה {{שכבה}}
- ברמת קושי {{רמת_קושי}}
- עם סוגי שאלות מגוונים (השלמה, כתיבה, בחירה, התאמה, בעיות מילוליות)
- מעוצב יפה להדפסה
- עם מקום לשם התלמיד ותאריך בראש הדף

אם רלוונטי, הוסף גם:
- דוגמאות ותרשימים עזר
- טבלאות או תבניות לפתרון
- הנחיות מיוחדות`,
    fields: [
      { id: 'מקצוע', label: 'מקצוע', placeholder: 'בחר מקצוע', type: 'select', options: ['מתמטיקה', 'עברית', 'אנגלית', 'מדעים', 'היסטוריה', 'גאוגרפיה', 'אזרחות', 'תנ"ך', 'ספרות', 'פיזיקה', 'כימיה', 'ביולוגיה', 'אחר'], required: true },
      { id: 'שכבה', label: 'שכבה', placeholder: 'בחר שכבה', type: 'select', options: ['א׳', 'ב׳', 'ג׳', 'ד׳', 'ה׳', 'ו׳', 'ז׳', 'ח׳', 'ט׳', 'י׳', 'י״א', 'י״ב'], required: true },
      { id: 'נושא', label: 'נושא התרגול', placeholder: 'שברים, דקדוק, מחזור המים...', type: 'text', required: true },
      { id: 'רמת_קושי', label: 'רמת קושי', placeholder: 'בחר רמה', type: 'select', options: ['קלה', 'בינונית', 'מאתגרת', 'מעורבת (כל הרמות)'], required: true },
      { id: 'מספר_תרגילים', label: 'מספר תרגילים', placeholder: 'כמות', type: 'select', options: ['5', '7', '10', '15', '20'], required: true },
      { id: 'פרטים', label: 'פרטים נוספים', placeholder: 'דגשים מיוחדים, נושאים משניים...', type: 'text', required: false }
    ],
    targetTools: ['ChatGPT', 'Claude', 'Gemini'],
    tips: 'פרומפט אוניברסלי שמתאים לכל מקצוע ונושא. ככל שתפרטו יותר בשדה "פרטים נוספים", הדף יהיה מותאם יותר לצרכים שלכם',
    createdBy: null,
    creatorName: 'מערכת',
    isAutoGenerated: true,
    status: 'active'
  },

  // ===== הכנת שיעורים =====
  {
    title: 'פתיחת שיעור מעניינת וסוחפת',
    description: 'רוצים לפתוח את השיעור בצורה שתגרום לתלמידים להתעניין? הנה הפתרון',
    category: 'הכנת שיעורים',
    subcategory: 'פתיחת שיעור מעניינת',
    promptTemplate: `אני מורה ל{{מקצוע}} בכיתה {{שכבה}}.
היום אני מלמד/ת על: {{נושא}}

אני רוצה ליצור "כרטיס כניסה" - פעילות קצרה (3-5 דקות) שתפתח את השיעור באנרגיה גבוהה ותעורר חשיבה.

סוג הפתיחה המועדף: {{סוג_פתיחה}}

אנא צור כרטיס כניסה שכולל:
1. שאלה/חידה/אתגר מעורר סקרנות
2. הוראות ברורות לתלמידים
3. קישור לנושא השיעור
4. אפשרות לעבודה {{צורת_עבודה}}`,
    fields: [
      { id: 'מקצוע', label: 'מקצוע', placeholder: 'מדעים', type: 'select', options: ['מתמטיקה', 'עברית', 'אנגלית', 'מדעים', 'היסטוריה', 'גאוגרפיה', 'אזרחות', 'תנ"ך', 'ספרות', 'אחר'], required: true },
      { id: 'שכבה', label: 'שכבה', placeholder: 'ד׳', type: 'select', options: ['א׳', 'ב׳', 'ג׳', 'ד׳', 'ה׳', 'ו׳', 'ז׳', 'ח׳', 'ט׳', 'י׳', 'י״א', 'י״ב'], required: true },
      { id: 'נושא', label: 'נושא השיעור', placeholder: 'מחזור המים', type: 'text', required: true },
      { id: 'סוג_פתיחה', label: 'סוג פתיחה', placeholder: 'חידה', type: 'select', options: ['חידה', 'שאלה מפתיעה', 'תמונה לניתוח', 'סיפור קצר', 'ניסוי מהיר', 'משחק מילים', 'סרטון קצר'], required: true },
      { id: 'צורת_עבודה', label: 'צורת עבודה', placeholder: 'זוגות', type: 'select', options: ['אישית', 'זוגות', 'קבוצות קטנות', 'כיתתית'], required: true }
    ],
    targetTools: ['ChatGPT', 'Claude', 'Gemini'],
    tips: 'כרטיס כניסה טוב מעורר סקרנות ומחבר את התלמידים לנושא עוד לפני שהתחלתם ללמד. נסו לגוון בין סוגים שונים',
    createdBy: null,
    creatorName: 'מערכת',
    isAutoGenerated: true,
    status: 'active'
  },

  // ===== תקשורת אישית =====
  {
    title: 'מכתב אישי לתלמיד',
    description: 'לפעמים מילה טובה בכתב יכולה לעשות פלאים - הנה תבנית למכתב מעצים',
    category: 'תקשורת אישית',
    subcategory: 'מכתב אישי לתלמיד',
    promptTemplate: `אני מורה ורוצה לכתוב מכתב אישי ומעצים לתלמיד/ה.

פרטים על התלמיד/ה:
- שם (או כינוי): {{שם}}
- שכבה: {{שכבה}}
- חוזקות שזיהיתי: {{חוזקות}}
- התקדמות/הישג אחרון: {{הישג}}

סיבת המכתב: {{סיבה}}

טון המכתב: {{טון}}

אנא כתוב מכתב אישי שיכלול:
1. פתיחה חמה ואישית
2. ציון ספציפי של מה שראיתי ומעריך/ה
3. עידוד להמשך הדרך
4. סיום מעצים

המכתב צריך להיות {{אורך}} ולהרגיש אותנטי ואישי.`,
    fields: [
      { id: 'שם', label: 'שם/כינוי התלמיד', placeholder: 'דנה', type: 'text', required: true },
      { id: 'שכבה', label: 'שכבה', placeholder: 'ה׳', type: 'select', options: ['א׳', 'ב׳', 'ג׳', 'ד׳', 'ה׳', 'ו׳', 'ז׳', 'ח׳', 'ט׳', 'י׳', 'י״א', 'י״ב'], required: true },
      { id: 'חוזקות', label: 'חוזקות שזיהיתי', placeholder: 'התמדה, עזרה לחברים...', type: 'text', required: true },
      { id: 'הישג', label: 'התקדמות/הישג', placeholder: 'שיפור משמעותי במבחן האחרון', type: 'text', required: false },
      { id: 'סיבה', label: 'סיבת המכתב', placeholder: 'סוף שנה, יום הולדת, הישג מיוחד...', type: 'select', options: ['סוף שנה', 'יום הולדת', 'הישג מיוחד', 'עידוד בתקופה קשה', 'פרידה', 'אחר'], required: true },
      { id: 'טון', label: 'טון המכתב', placeholder: 'חם ומעודד', type: 'select', options: ['חם ומעודד', 'רשמי יותר', 'הומוריסטי', 'רגשי'], required: true },
      { id: 'אורך', label: 'אורך המכתב', placeholder: 'בינוני', type: 'select', options: ['קצר (פסקה)', 'בינוני (2-3 פסקאות)', 'ארוך (עמוד)'], required: true }
    ],
    targetTools: ['ChatGPT', 'Claude', 'Gemini'],
    tips: 'ככל שתפרטו יותר על התלמיד, המכתב יהיה אישי ואותנטי יותר. מומלץ לערוך ולהוסיף נגיעות אישיות משלכם לפני השליחה',
    createdBy: null,
    creatorName: 'מערכת',
    isAutoGenerated: true,
    status: 'active'
  },

  // ===== למידה חברתית-רגשית (SEL) =====
  {
    title: 'מערך שיעור חברתי-רגשי',
    description: 'בניית מערך שיעור מסודר בנושאי SEL - רגשות, אמפתיה, שיתוף פעולה',
    category: 'למידה חברתית-רגשית (SEL)',
    subcategory: 'מערך שיעור חברתי',
    promptTemplate: `אני מורה/ת בכיתה {{שכבה}} ורוצה לקיים שיעור חברתי-רגשי (SEL).

תחום ה-SEL שאני רוצה להתמקד בו: {{תחום_sel}}

נושא ספציפי: {{נושא}}

משך השיעור: {{משך}}

אנא בנה/י מערך שיעור הכולל:
1. פתיחה - פעילות חימום רגשי (5 דקות)
2. הצגת הנושא - דרך סיפור/סרטון/מקרה לדיון
3. פעילות מרכזית - התנסות מעשית
4. דיון כיתתי מונחה עם שאלות מנחות
5. סיכום ותרגול אישי/קבוצתי
6. משימת המשך (אופציונלי)

התאם/י לגיל ולעולם התוכן של התלמידים.`,
    fields: [
      { id: 'שכבה', label: 'שכבה', placeholder: 'ד׳', type: 'select', options: ['א׳', 'ב׳', 'ג׳', 'ד׳', 'ה׳', 'ו׳', 'ז׳', 'ח׳', 'ט׳', 'י׳', 'י״א', 'י״ב'], required: true },
      { id: 'תחום_sel', label: 'תחום SEL', placeholder: 'מודעות עצמית', type: 'select', options: ['מודעות עצמית', 'ניהול עצמי', 'מודעות חברתית', 'מיומנויות יחסים', 'קבלת החלטות אחראית'], required: true },
      { id: 'נושא', label: 'נושא ספציפי', placeholder: 'זיהוי רגשות, התמודדות עם כעס...', type: 'text', required: true },
      { id: 'משך', label: 'משך השיעור', placeholder: '45 דקות', type: 'select', options: ['30 דקות', '45 דקות', '60 דקות', '90 דקות'], required: true }
    ],
    targetTools: ['ChatGPT', 'Claude', 'Gemini'],
    tips: 'מודל CASEL כולל 5 תחומים: מודעות עצמית, ניהול עצמי, מודעות חברתית, מיומנויות יחסים, וקבלת החלטות אחראית. בחרו תחום אחד להתמקד בו',
    createdBy: null,
    creatorName: 'מערכת',
    isAutoGenerated: true,
    status: 'active'
  },
  {
    title: 'פעילות לפיתוח מיומנויות SEL',
    description: 'פעילות ממוקדת לפיתוח מיומנות חברתית-רגשית ספציפית',
    category: 'למידה חברתית-רגשית (SEL)',
    subcategory: 'פעילות מיומנויות SEL',
    promptTemplate: `אני מחפש/ת פעילות קצרה לפיתוח מיומנויות SEL בכיתה {{שכבה}}.

מיומנות ספציפית לפיתוח: {{מיומנות}}

הקשר הפעילות: {{הקשר}}

משך הפעילות: {{משך}}

סוג פעילות מועדף: {{סוג}}

אנא תכנן/י פעילות שכוללת:
1. מטרת הפעילות והמיומנות שתפותח
2. החומרים הנדרשים
3. הוראות שלב אחר שלב
4. שאלות לרפלקציה
5. וריאציות או הרחבות אפשריות`,
    fields: [
      { id: 'שכבה', label: 'שכבה', placeholder: 'ג׳', type: 'select', options: ['א׳', 'ב׳', 'ג׳', 'ד׳', 'ה׳', 'ו׳', 'ז׳', 'ח׳', 'ט׳', 'י׳', 'י״א', 'י״ב'], required: true },
      { id: 'מיומנות', label: 'מיומנות לפיתוח', placeholder: 'אמפתיה, ויסות רגשי...', type: 'text', required: true },
      { id: 'הקשר', label: 'הקשר הפעילות', placeholder: 'שיעור חברתי, אחרי אירוע קשה...', type: 'select', options: ['שיעור חברתי שבועי', 'פתיחת יום', 'אחרי הפסקה', 'אחרי אירוע/קונפליקט', 'סיום יום'], required: true },
      { id: 'משך', label: 'משך הפעילות', placeholder: '15 דקות', type: 'select', options: ['5 דקות', '10 דקות', '15 דקות', '20 דקות', '30 דקות'], required: true },
      { id: 'סוג', label: 'סוג פעילות', placeholder: 'עבודת צוות', type: 'select', options: ['דיון כיתתי', 'עבודת צוות', 'יצירה אישית', 'משחק תפקידים', 'תנועה/דרמה', 'כתיבה רפלקטיבית'], required: true }
    ],
    targetTools: ['ChatGPT', 'Claude', 'Gemini'],
    tips: 'פעילויות SEL קצרות ועקביות יעילות יותר מפעילויות ארוכות חד-פעמיות. תכננו סדרת פעילויות לאורך השנה',
    createdBy: null,
    creatorName: 'מערכת',
    isAutoGenerated: true,
    status: 'active'
  },
  {
    title: 'משחק תפקידים לתרגול מיומנויות חברתיות',
    description: 'תרחישים למשחק תפקידים שמאפשרים תרגול מצבים חברתיים',
    category: 'למידה חברתית-רגשית (SEL)',
    subcategory: 'משחק תפקידים',
    promptTemplate: `אני רוצה לקיים משחק תפקידים בכיתה {{שכבה}} לתרגול מיומנויות חברתיות-רגשיות.

הסיטואציה/נושא: {{סיטואציה}}

מיומנויות לתרגול: {{מיומנויות}}

מספר משתתפים: {{מספר_משתתפים}}

אנא צור תרחיש למשחק תפקידים שכולל:
1. רקע הסיטואציה
2. תיאור הדמויות והתפקידים
3. הנחיות לשחקנים
4. נקודות למעקב לצופים
5. שאלות לדיון אחרי המשחק
6. וריאציות אפשריות לסיטואציה`,
    fields: [
      { id: 'שכבה', label: 'שכבה', placeholder: 'ה׳', type: 'select', options: ['א׳', 'ב׳', 'ג׳', 'ד׳', 'ה׳', 'ו׳', 'ז׳', 'ח׳', 'ט׳', 'י׳', 'י״א', 'י״ב'], required: true },
      { id: 'סיטואציה', label: 'סיטואציה/נושא', placeholder: 'קונפליקט בהפסקה, לחץ חברתי...', type: 'text', required: true },
      { id: 'מיומנויות', label: 'מיומנויות לתרגול', placeholder: 'אסרטיביות, פתרון קונפליקטים...', type: 'text', required: true },
      { id: 'מספר_משתתפים', label: 'מספר משתתפים', placeholder: '3-4', type: 'select', options: ['2 תלמידים', '3-4 תלמידים', '5-6 תלמידים', 'כל הכיתה'], required: true }
    ],
    targetTools: ['ChatGPT', 'Claude', 'Gemini'],
    tips: 'לפני משחק התפקידים, הסבירו לתלמידים שזו התנסות בטוחה ושאין תשובות נכונות או לא נכונות. צרו אווירה תומכת',
    createdBy: null,
    creatorName: 'מערכת',
    isAutoGenerated: true,
    status: 'active'
  },
  {
    title: 'פעילות לבניית אופטימיות וחוסן נפשי',
    description: 'פעילות המחזקת חשיבה חיובית, אופטימיות ויכולת התמודדות',
    category: 'למידה חברתית-רגשית (SEL)',
    subcategory: 'פעילות אופטימיות וחוסן',
    promptTemplate: `אני רוצה לקיים פעילות SEL קצרה בנושא אופטימיות וחוסן בכיתה {{שכבה}}.

מטרת הפעילות: {{מטרה}}

משך הפעילות: {{משך}}

ההקשר: {{הקשר}}

אנא תכנן/י פעילות "לראות את האור" שכוללת:
1. פתיחה עם דימוי ויזואלי (מטאפורה של אור/חושך)
2. פעילות מרכזית לחיזוק חשיבה אופטימית
3. שיתוף ודיון
4. כלי מעשי שהתלמידים יכולים לקחת איתם
5. סיכום מעצים

הפעילות צריכה להיות מתאימה לגיל ולתת כלים מעשיים להתמודדות.`,
    fields: [
      { id: 'שכבה', label: 'שכבה', placeholder: 'ד׳', type: 'select', options: ['א׳', 'ב׳', 'ג׳', 'ד׳', 'ה׳', 'ו׳', 'ז׳', 'ח׳', 'ט׳', 'י׳', 'י״א', 'י״ב'], required: true },
      { id: 'מטרה', label: 'מטרה עיקרית', placeholder: 'התמודדות עם קשיים', type: 'select', options: ['התמודדות עם קשיים', 'מציאת הטוב בכל יום', 'בניית חוסן', 'תקווה ואופטימיות', 'הכרת תודה'], required: true },
      { id: 'משך', label: 'משך הפעילות', placeholder: '20 דקות', type: 'select', options: ['10 דקות', '15 דקות', '20 דקות', '30 דקות'], required: true },
      { id: 'הקשר', label: 'הקשר הפעילות', placeholder: 'שיעור חברתי', type: 'select', options: ['שיעור חברתי', 'פתיחת שבוע', 'אחרי אירוע קשה', 'תקופת מבחנים', 'סוף שנה'], required: true }
    ],
    targetTools: ['ChatGPT', 'Claude', 'Gemini'],
    tips: 'המטאפורה של אור וחושך עוזרת לתלמידים להבין רגשות בצורה חזותית ולא מאיימת. השתמשו בה גם בשיחות אישיות',
    createdBy: null,
    creatorName: 'מערכת',
    isAutoGenerated: true,
    status: 'active'
  }
];

/**
 * Seed prompts to Firestore
 * Deletes old worksheet prompts (including the new one to avoid duplicates), then adds new ones
 * Returns: number of prompts added
 */
export async function seedPrompts(): Promise<number> {
  // Step 1: Delete old worksheet prompts (3 old + 1 new to prevent duplicates)
  console.log('🗑️ Deleting old worksheet prompts...');
  const worksheetTitlesToDelete = [
    'דף עבודה בעברית/לשון',
    'דף עבודה במתמטיקה',
    'דף תרגול כללי',
    'דף עבודה להדפסה'  // Also delete the new one to prevent duplicates
  ];

  let deletedCount = 0;
  const deleteBatch = db.batch();

  for (const title of worksheetTitlesToDelete) {
    const oldPrompts = await db.collection('prompts')
      .where('title', '==', title)
      .get();

    oldPrompts.docs.forEach(doc => {
      deleteBatch.delete(doc.ref);
      deletedCount++;
    });
  }

  if (deletedCount > 0) {
    await deleteBatch.commit();
    console.log(`✅ Deleted ${deletedCount} old worksheet prompts`);
  }

  // Step 2: Add new prompts
  console.log(`🌱 Starting to seed ${SEED_PROMPTS.length} new prompts...`);

  let addedCount = 0;
  const batch = db.batch();

  for (const prompt of SEED_PROMPTS) {
    const promptRef = db.collection('prompts').doc();

    batch.set(promptRef, {
      ...prompt,
      createdAt: FieldValue.serverTimestamp(),
      usageCount: 0,
      averageRating: 0,
      ratingCount: 0
    });

    addedCount++;
  }

  await batch.commit();
  console.log(`✅ Successfully seeded ${addedCount} prompts!`);

  return addedCount;
}
