import React, { useState } from 'react';
import {
  IconX,
  IconPlus,
  IconTrash,
  IconGripVertical,
  IconSparkles,
  IconCheck,
  IconAlertCircle
} from '@tabler/icons-react';
import type { PromptField } from '../services/promptsService';
import {
  createPrompt,
  PROMPT_CATEGORIES,
  COMMON_FIELD_OPTIONS
} from '../services/promptsService';
import { useAuth } from '../context/AuthContext';

interface SubmitPromptModalProps {
  onClose: () => void;
  onSubmit: () => void;
}

interface FieldDefinition extends PromptField {
  tempId: string;
}

export default function SubmitPromptModal({ onClose, onSubmit }: SubmitPromptModalProps) {
  const { currentUser } = useAuth();
  const [step, setStep] = useState<1 | 2 | 3>(1);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Step 1: Basic Info
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [categoryId, setCategoryId] = useState('');
  const [subcategory, setSubcategory] = useState('');
  const [targetTools, setTargetTools] = useState<string[]>(['ChatGPT', 'Claude', 'Gemini']);
  const [tips, setTips] = useState('');

  // Step 2: Prompt Template with Fields
  const [promptTemplate, setPromptTemplate] = useState('');
  const [fields, setFields] = useState<FieldDefinition[]>([]);

  // Get selected category data
  const selectedCategory = PROMPT_CATEGORIES.find(c => c.id === categoryId);

  const addField = () => {
    const newField: FieldDefinition = {
      tempId: `field_${Date.now()}`,
      id: `field_${Date.now()}`,
      label: '',
      placeholder: '',
      type: 'text',
      required: true
    };
    setFields([...fields, newField]);
  };

  const updateField = (tempId: string, updates: Partial<FieldDefinition>) => {
    setFields(fields.map(f =>
      f.tempId === tempId ? { ...f, ...updates } : f
    ));
  };

  const removeField = (tempId: string) => {
    setFields(fields.filter(f => f.tempId !== tempId));
  };

  const insertFieldPlaceholder = (fieldId: string) => {
    const placeholder = `{{${fieldId}}}`;
    setPromptTemplate(prev => prev + placeholder);
  };

  const toggleTool = (tool: string) => {
    setTargetTools(prev =>
      prev.includes(tool)
        ? prev.filter(t => t !== tool)
        : [...prev, tool]
    );
  };

  const validateStep1 = () => {
    if (!title.trim()) return 'נא להזין כותרת';
    if (!description.trim()) return 'נא להזין תיאור';
    if (!categoryId) return 'נא לבחור קטגוריה';
    if (!subcategory) return 'נא לבחור תת-קטגוריה';
    if (targetTools.length === 0) return 'נא לבחור לפחות כלי AI אחד';
    return null;
  };

  const validateStep2 = () => {
    if (!promptTemplate.trim()) return 'נא להזין את תבנית הפרומפט';
    if (fields.some(f => !f.label.trim())) return 'נא למלא את כל שמות השדות';
    // Check all fields are used in template
    const unusedFields = fields.filter(f => !promptTemplate.includes(`{{${f.id}}}`));
    if (unusedFields.length > 0) {
      return `השדות הבאים לא נמצאים בתבנית: ${unusedFields.map(f => f.label).join(', ')}`;
    }
    return null;
  };

  const handleNext = () => {
    if (step === 1) {
      const error = validateStep1();
      if (error) {
        setError(error);
        return;
      }
      setError(null);
      setStep(2);
    } else if (step === 2) {
      const error = validateStep2();
      if (error) {
        setError(error);
        return;
      }
      setError(null);
      setStep(3);
    }
  };

  const handleSubmit = async () => {
    if (!currentUser) {
      setError('יש להתחבר כדי להציע פרומפט');
      return;
    }

    setIsSubmitting(true);
    setError(null);

    try {
      // Clean up field IDs to use label as ID
      const cleanedFields: PromptField[] = fields.map(f => ({
        id: f.label,
        label: f.label,
        placeholder: f.placeholder,
        type: f.type,
        options: f.options,
        required: f.required
      }));

      // Replace temp IDs with labels in template
      let cleanedTemplate = promptTemplate;
      fields.forEach(f => {
        cleanedTemplate = cleanedTemplate.replace(
          new RegExp(`\\{\\{${f.id}\\}\\}`, 'g'),
          `{{${f.label}}}`
        );
      });

      await createPrompt({
        title,
        description,
        category: selectedCategory?.name || '',
        subcategory,
        promptTemplate: cleanedTemplate,
        fields: cleanedFields,
        targetTools,
        tips: tips || undefined,
        createdBy: currentUser.uid,
        creatorName: currentUser.displayName || 'מורה אנונימי',
        isAutoGenerated: false,
        status: 'active' // Goes live immediately
      });

      onSubmit();
    } catch (err) {
      console.error('Error submitting prompt:', err);
      setError('שגיאה בשליחת הפרומפט. נסה שוב.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const availableTools = ['ChatGPT', 'Claude', 'Gemini', 'Copilot', 'Perplexity'];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm" dir="rtl">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="p-6 border-b border-slate-200 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-wizdi-royal/10 rounded-xl flex items-center justify-center">
              <IconSparkles className="w-6 h-6 text-wizdi-royal" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-slate-800">הצעת פרומפט חדש</h2>
              <p className="text-sm text-slate-500">שלב {step} מתוך 3</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-slate-100 rounded-xl transition-all"
          >
            <IconX className="w-6 h-6 text-slate-500" />
          </button>
        </div>

        {/* Progress Bar */}
        <div className="px-6 pt-4">
          <div className="flex gap-2">
            {[1, 2, 3].map(s => (
              <div
                key={s}
                className={`h-2 flex-1 rounded-full transition-all ${
                  s <= step ? 'bg-wizdi-royal' : 'bg-slate-200'
                }`}
              />
            ))}
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          {error && (
            <div className="mb-4 p-4 bg-red-50 border border-red-200 rounded-xl flex items-center gap-3 text-red-700">
              <IconAlertCircle className="w-5 h-5 flex-shrink-0" />
              <span className="text-sm">{error}</span>
            </div>
          )}

          {/* Step 1: Basic Info */}
          {step === 1 && (
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">
                  כותרת הפרומפט <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="לדוגמה: יצירת מבחן רב-ברירה"
                  className="w-full px-4 py-3 border border-slate-200 rounded-xl focus:border-wizdi-royal focus:ring-2 focus:ring-wizdi-royal/20 outline-none transition-all"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">
                  תיאור קצר <span className="text-red-500">*</span>
                </label>
                <textarea
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="תאר בקצרה למה הפרומפט מתאים ומה הוא עושה"
                  rows={2}
                  className="w-full px-4 py-3 border border-slate-200 rounded-xl focus:border-wizdi-royal focus:ring-2 focus:ring-wizdi-royal/20 outline-none transition-all resize-none"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">
                    קטגוריה <span className="text-red-500">*</span>
                  </label>
                  <select
                    value={categoryId}
                    onChange={(e) => {
                      setCategoryId(e.target.value);
                      setSubcategory('');
                    }}
                    className="w-full px-4 py-3 border border-slate-200 rounded-xl focus:border-wizdi-royal focus:ring-2 focus:ring-wizdi-royal/20 outline-none transition-all"
                  >
                    <option value="">בחר קטגוריה</option>
                    {PROMPT_CATEGORIES.map(cat => (
                      <option key={cat.id} value={cat.id}>
                        {cat.icon} {cat.name}
                      </option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">
                    תת-קטגוריה <span className="text-red-500">*</span>
                  </label>
                  <select
                    value={subcategory}
                    onChange={(e) => setSubcategory(e.target.value)}
                    disabled={!selectedCategory}
                    className="w-full px-4 py-3 border border-slate-200 rounded-xl focus:border-wizdi-royal focus:ring-2 focus:ring-wizdi-royal/20 outline-none transition-all disabled:bg-slate-100 disabled:cursor-not-allowed"
                  >
                    <option value="">בחר תת-קטגוריה</option>
                    {selectedCategory?.subcategories.map(sub => (
                      <option key={sub} value={sub}>{sub}</option>
                    ))}
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 mb-2">
                  כלי AI מתאימים <span className="text-red-500">*</span>
                </label>
                <div className="flex flex-wrap gap-2">
                  {availableTools.map(tool => (
                    <button
                      key={tool}
                      type="button"
                      onClick={() => toggleTool(tool)}
                      className={`px-4 py-2 rounded-full text-sm font-medium transition-all ${
                        targetTools.includes(tool)
                          ? 'bg-wizdi-royal text-white'
                          : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
                      }`}
                    >
                      {tool}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">
                  טיפ לשימוש (אופציונלי)
                </label>
                <input
                  type="text"
                  value={tips}
                  onChange={(e) => setTips(e.target.value)}
                  placeholder="טיפ קצר למורים שישתמשו בפרומפט"
                  className="w-full px-4 py-3 border border-slate-200 rounded-xl focus:border-wizdi-royal focus:ring-2 focus:ring-wizdi-royal/20 outline-none transition-all"
                />
              </div>
            </div>
          )}

          {/* Step 2: Template and Fields */}
          {step === 2 && (
            <div className="space-y-6">
              {/* Fields Definition */}
              <div>
                <div className="flex items-center justify-between mb-3">
                  <label className="text-sm font-medium text-slate-700">
                    שדות דינמיים
                  </label>
                  <button
                    type="button"
                    onClick={addField}
                    className="flex items-center gap-1 px-3 py-1.5 text-sm bg-wizdi-royal/10 text-wizdi-royal rounded-lg hover:bg-wizdi-royal/20 transition-all"
                  >
                    <IconPlus className="w-4 h-4" />
                    הוסף שדה
                  </button>
                </div>

                {fields.length === 0 ? (
                  <div className="text-center py-8 bg-slate-50 rounded-xl border-2 border-dashed border-slate-200">
                    <p className="text-slate-500 mb-2">אין שדות דינמיים</p>
                    <p className="text-xs text-slate-400">
                      הוסף שדות שהמורה ימלא לפני העתקת הפרומפט
                    </p>
                  </div>
                ) : (
                  <div className="space-y-3">
                    {fields.map((field, index) => (
                      <div
                        key={field.tempId}
                        className="p-4 bg-slate-50 rounded-xl border border-slate-200"
                      >
                        <div className="flex items-start gap-3">
                          <IconGripVertical className="w-5 h-5 text-slate-400 mt-2 cursor-grab" />
                          <div className="flex-1 grid grid-cols-2 gap-3">
                            <div>
                              <label className="text-xs text-slate-500 mb-1 block">שם השדה</label>
                              <input
                                type="text"
                                value={field.label}
                                onChange={(e) => updateField(field.tempId, {
                                  label: e.target.value,
                                  id: e.target.value.replace(/\s+/g, '_')
                                })}
                                placeholder="לדוגמה: מקצוע"
                                className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm"
                              />
                            </div>
                            <div>
                              <label className="text-xs text-slate-500 mb-1 block">סוג</label>
                              <select
                                value={field.type}
                                onChange={(e) => updateField(field.tempId, {
                                  type: e.target.value as 'text' | 'select' | 'number'
                                })}
                                className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm"
                              >
                                <option value="text">טקסט חופשי</option>
                                <option value="select">בחירה מרשימה</option>
                                <option value="number">מספר</option>
                              </select>
                            </div>
                            <div className="col-span-2">
                              <label className="text-xs text-slate-500 mb-1 block">טקסט עזרה</label>
                              <input
                                type="text"
                                value={field.placeholder}
                                onChange={(e) => updateField(field.tempId, { placeholder: e.target.value })}
                                placeholder="לדוגמה: מתמטיקה, עברית..."
                                className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm"
                              />
                            </div>
                            {field.type === 'select' && (
                              <div className="col-span-2">
                                <label className="text-xs text-slate-500 mb-1 block">אפשרויות (מופרד בפסיקים)</label>
                                <input
                                  type="text"
                                  value={field.options?.join(', ') || ''}
                                  onChange={(e) => updateField(field.tempId, {
                                    options: e.target.value.split(',').map(s => s.trim()).filter(Boolean)
                                  })}
                                  placeholder="אפשרות 1, אפשרות 2, אפשרות 3"
                                  className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm"
                                />
                                {/* Quick options */}
                                <div className="flex flex-wrap gap-1 mt-2">
                                  <button
                                    type="button"
                                    onClick={() => updateField(field.tempId, { options: COMMON_FIELD_OPTIONS.subjects })}
                                    className="px-2 py-1 text-xs bg-slate-200 rounded hover:bg-slate-300"
                                  >
                                    מקצועות
                                  </button>
                                  <button
                                    type="button"
                                    onClick={() => updateField(field.tempId, { options: COMMON_FIELD_OPTIONS.gradeLevels })}
                                    className="px-2 py-1 text-xs bg-slate-200 rounded hover:bg-slate-300"
                                  >
                                    שכבות
                                  </button>
                                  <button
                                    type="button"
                                    onClick={() => updateField(field.tempId, { options: COMMON_FIELD_OPTIONS.difficultyLevels })}
                                    className="px-2 py-1 text-xs bg-slate-200 rounded hover:bg-slate-300"
                                  >
                                    רמות קושי
                                  </button>
                                </div>
                              </div>
                            )}
                          </div>
                          <div className="flex flex-col gap-2">
                            <button
                              type="button"
                              onClick={() => insertFieldPlaceholder(field.id)}
                              className="p-2 text-wizdi-royal hover:bg-wizdi-royal/10 rounded-lg transition-all"
                              title="הוסף לתבנית"
                            >
                              <IconPlus className="w-4 h-4" />
                            </button>
                            <button
                              type="button"
                              onClick={() => removeField(field.tempId)}
                              className="p-2 text-red-500 hover:bg-red-50 rounded-lg transition-all"
                            >
                              <IconTrash className="w-4 h-4" />
                            </button>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Template */}
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-2">
                  תבנית הפרומפט <span className="text-red-500">*</span>
                </label>
                <p className="text-xs text-slate-500 mb-2">
                  השתמש ב-{`{{שם_שדה}}`} להוספת שדות דינמיים. לחץ על + ליד כל שדה להוספה אוטומטית.
                </p>
                <textarea
                  value={promptTemplate}
                  onChange={(e) => setPromptTemplate(e.target.value)}
                  placeholder={`לדוגמה: אתה מורה ל{{מקצוע}} בכיתה {{שכבה}}. הכן לי {{סוג_פעילות}} בנושא {{נושא}}.`}
                  rows={8}
                  className="w-full px-4 py-3 border border-slate-200 rounded-xl focus:border-wizdi-royal focus:ring-2 focus:ring-wizdi-royal/20 outline-none transition-all resize-none font-mono text-sm"
                  dir="rtl"
                />
              </div>
            </div>
          )}

          {/* Step 3: Preview */}
          {step === 3 && (
            <div className="space-y-6">
              <div className="text-center mb-6">
                <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                  <IconCheck className="w-8 h-8 text-green-600" />
                </div>
                <h3 className="text-xl font-bold text-slate-800">הפרומפט מוכן!</h3>
                <p className="text-slate-500">בדוק את התצוגה המקדימה לפני השליחה</p>
              </div>

              <div className="bg-slate-50 rounded-xl p-4 border border-slate-200">
                <h4 className="font-bold text-slate-800 mb-2">{title}</h4>
                <p className="text-sm text-slate-600 mb-3">{description}</p>
                <div className="flex items-center gap-2 text-xs text-slate-500 mb-3">
                  <span className="px-2 py-1 bg-white rounded-full">
                    {selectedCategory?.icon} {selectedCategory?.name}
                  </span>
                  <span className="px-2 py-1 bg-white rounded-full">{subcategory}</span>
                </div>
                <div className="bg-slate-800 rounded-lg p-4 text-white text-sm font-mono">
                  <pre className="whitespace-pre-wrap" dir="rtl">{promptTemplate}</pre>
                </div>
                {fields.length > 0 && (
                  <div className="mt-3">
                    <p className="text-xs text-slate-500 mb-2">שדות:</p>
                    <div className="flex flex-wrap gap-2">
                      {fields.map(f => (
                        <span key={f.tempId} className="px-2 py-1 bg-wizdi-royal/10 text-wizdi-royal text-xs rounded">
                          {f.label} ({f.type === 'text' ? 'טקסט' : f.type === 'select' ? 'בחירה' : 'מספר'})
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </div>

              <div className="p-4 bg-blue-50 rounded-xl border border-blue-100">
                <p className="text-sm text-blue-700">
                  <strong>שים לב:</strong> הפרומפט יעלה מיד לאוויר עם השם שלך.
                  מורים אחרים יוכלו לדרג אותו ולהשתמש בו.
                </p>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-slate-200 flex items-center justify-between">
          <button
            onClick={step === 1 ? onClose : () => setStep((step - 1) as 1 | 2)}
            className="px-6 py-3 text-slate-600 hover:bg-slate-100 rounded-xl transition-all"
          >
            {step === 1 ? 'ביטול' : 'הקודם'}
          </button>

          {step < 3 ? (
            <button
              onClick={handleNext}
              className="px-6 py-3 bg-wizdi-royal text-white rounded-xl hover:bg-wizdi-royal/90 transition-all font-medium"
            >
              הבא
            </button>
          ) : (
            <button
              onClick={handleSubmit}
              disabled={isSubmitting}
              className="px-6 py-3 bg-wizdi-lime text-slate-800 rounded-xl hover:bg-wizdi-lime/90 transition-all font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
            >
              {isSubmitting ? (
                <>
                  <div className="w-5 h-5 border-2 border-slate-800/30 border-t-slate-800 rounded-full animate-spin" />
                  שולח...
                </>
              ) : (
                <>
                  <IconCheck className="w-5 h-5" />
                  שלח פרומפט
                </>
              )}
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
