import type { ActivityBlockType, BloomLevel, StrictBlockContent, RichOption } from './courseTypes';

/**
 * Represents the distinct "Raw" structure returned by the AI.
 * The AI is instructed to return specific JSON formats, but often varies nesting.
 * This interface attempts to capture the "Union" of all observed variations.
 */
export interface RawAiItem {
    // Top-level variations
    type?: string;
    selected_interaction?: string;
    bloom_level?: string;

    // Nesting wrappers
    data?: RawAiItem | any; // Sometimes nested as { data: { ... } }
    interactive_question?: RawAiItem;

    // Question Text Variations
    question?: string | { text: string };
    question_text?: string;
    text?: string;
    content?: string;
    instruction?: string;
    description?: string;
    max_duration?: number;

    // Feedback
    feedback?: string;
    feedback_correct?: string;
    feedback_incorrect?: string;

    // Scaffolding
    source_reference?: string;
    source_reference_hint?: string;
    progressive_hints?: string[];
    teacher_guidelines?: string;
    model_answer?: string;
    answer_key?: string;

    // Multiple Choice / General Options
    options?: (string | RichOption)[];
    choices?: (string | RichOption)[];
    answers?: (string | RichOption)[];
    correct_answer?: string;
    correct_index?: number;

    // Ordering / Sequencing
    items?: (string | { text?: string; step?: string; content?: string; category?: string; group?: string; group_index?: number })[];
    steps?: string[];
    correct_order?: string[];

    // Categorization / Matching
    cards?: any[];
    pairs?: { left?: string; item?: string; right?: string; category?: string; card_a?: string; card_b?: string }[];
    groups?: string[];
    categories?: string[];

    // Fill in Blanks
    word_bank?: string[];
}

// Moved to courseTypes.ts

/**
 * Strict content definitions for the Mapped Blocks.
 * These replace the generic 'any' in ActivityBlock.content during processing.
 */

// Strict Content Definitions are now in courseTypes.ts

/**
 * The normalized block returned by mapSystemItemToBlock
 */
export interface MappedLearningBlock {
    id: string;
    type: ActivityBlockType;
    content: StrictBlockContent;
    metadata: {
        bloomLevel: BloomLevel | string;
        score: number;
        feedbackCorrect?: string;
        feedbackIncorrect?: string;
        sourceReference?: string | null;
        progressiveHints?: string[];
        richOptions?: any[]; // Keep rich data if available
        modelAnswer?: string;
        [key: string]: any;
    };
}

/**
 * Structure of the Unit Skeleton generated by the "Brain"
 */
export interface SkeletonStep {
    step_number: number;
    title: string;
    narrative_focus: string;
    forbidden_topics: string[];
    bloom_level: string;
    suggested_interaction_type: string;
}

export interface UnitSkeleton {
    unit_title: string;
    steps: SkeletonStep[];
}

/**
 * Structure of the Step Content generated by the "Hands"
 */
export interface StepContentResponse {
    step_number: number;
    bloom_level: string;
    teach_content: string;
    selected_interaction: string;
    data: RawAiItem; // This is the raw data we map later
}

// --- AUDIO OVERVIEW TYPES (NotebookLM Features) ---

export interface AudioOverviewRequest {
    sourceText: string;
    focusTopic?: string;
    targetAudience: string; // "Student", "Teacher", "Child"
    language: 'he' | 'en';
}

export interface DialogueLine {
    speaker: 'Dan' | 'Noa';
    text: string;
    emotion?: 'Curious' | 'Skeptical' | 'Excited' | 'Neutral';
}

export interface DialogueScript {
    title: string;
    lines: DialogueLine[];
}

export interface AudioOverviewResponse {
    script: DialogueScript;
    audioUrl?: string; // Optional, populated after TTS
}

export interface SourceGuideData {
    summary: string;
    topics: { term: string; definition: string }[];
    faq: { question: string; answer: string }[];
}

