import type { ActivityBlockType, BloomLevel, StrictBlockContent, RichOption } from './courseTypes';

/**
 * Represents the distinct "Raw" structure returned by the AI.
 * The AI is instructed to return specific JSON formats, but often varies nesting.
 * This interface attempts to capture the "Union" of all observed variations.
 */
export interface RawAiItem {
    // Top-level variations
    type?: string;
    selected_interaction?: string;
    bloom_level?: string;

    // Nesting wrappers
    data?: RawAiItem | any; // Sometimes nested as { data: { ... } }
    interactive_question?: RawAiItem;

    // Question Text Variations
    question?: string | { text: string };
    question_text?: string;
    text?: string;
    content?: string;
    instruction?: string;
    description?: string;
    max_duration?: number;

    // Feedback
    feedback?: string;
    feedback_correct?: string;
    feedback_incorrect?: string;

    // Scaffolding
    source_reference?: string;
    source_reference_hint?: string;
    progressive_hints?: string[];
    teacher_guidelines?: string;
    model_answer?: string;
    answer_key?: string;

    // Multiple Choice / General Options
    options?: (string | RichOption)[];
    choices?: (string | RichOption)[];
    answers?: (string | RichOption)[];
    correct_answer?: string;
    correct_index?: number;

    // Ordering / Sequencing
    items?: (string | { text?: string; step?: string; content?: string; category?: string; group?: string; group_index?: number })[];
    steps?: string[];
    correct_order?: string[];

    // Categorization / Matching
    cards?: any[];
    pairs?: { left?: string; item?: string; right?: string; category?: string; card_a?: string; card_b?: string }[];
    groups?: string[];
    categories?: string[];

    // Fill in Blanks
    word_bank?: string[];
}

// Moved to courseTypes.ts

/**
 * Strict content definitions for the Mapped Blocks.
 * These replace the generic 'any' in ActivityBlock.content during processing.
 */

// Strict Content Definitions are now in courseTypes.ts

/**
 * The normalized block returned by mapSystemItemToBlock
 */
export interface MappedLearningBlock {
    id: string;
    type: ActivityBlockType;
    content: StrictBlockContent;
    metadata: {
        bloomLevel: BloomLevel | string;
        score: number;
        feedbackCorrect?: string;
        feedbackIncorrect?: string;
        sourceReference?: string | null;
        progressiveHints?: string[];
        richOptions?: any[]; // Keep rich data if available
        modelAnswer?: string;
        [key: string]: any;
    };
}

/**
 * Structure of the Unit Skeleton generated by the "Brain"
 */
export interface SkeletonStep {
    step_number: number;
    title: string;
    narrative_focus: string;
    forbidden_topics: string[];
    bloom_level: string;
    suggested_interaction_type: string;
}

export interface UnitSkeleton {
    unit_title: string;
    steps: SkeletonStep[];
    context_image_prompt?: string; // AI-generated prompt for opening image
}

/**
 * Media suggestion returned by AI for each step
 */
export interface SuggestedMedia {
    needed: boolean;
    type?: 'scenario_image' | 'infographic';
    infographic_type?: 'flowchart' | 'timeline' | 'comparison' | 'cycle';
    prompt_hint?: string;
}

/**
 * Structure of the Step Content generated by the "Hands"
 */
export interface StepContentResponse {
    step_number: number;
    bloom_level: string;
    teach_content: string;
    selected_interaction: string;
    data: RawAiItem; // This is the raw data we map later
    suggested_media?: SuggestedMedia; // AI suggestion for image/infographic
}

// --- AUDIO OVERVIEW TYPES (NotebookLM Features) ---

export interface AudioOverviewRequest {
    sourceText: string;
    focusTopic?: string;
    targetAudience: string; // "Student", "Teacher", "Child"
    language: 'he' | 'en';
}

export interface DialogueLine {
    speaker: 'Dan' | 'Noa';
    text: string;
    emotion?: 'Curious' | 'Skeptical' | 'Excited' | 'Neutral';
}

export interface DialogueScript {
    title: string;
    lines: DialogueLine[];
}

export interface AudioOverviewResponse {
    script: DialogueScript;
    audioUrl?: string; // Optional, populated after TTS
}

export interface SourceGuideData {
    summary: string;
    topics: { term: string; definition: string }[];
    faq: { question: string; answer: string }[];
}

// === TEACHER LESSON PLAN ARCHITECTURE (Master Teacher V4 - Enhanced) ===

export type MediaAssetType = 'image_description' | 'youtube_timestamp' | 'ai_generated_image' | 'infographic' | 'none';

export interface MediaAsset {
    type: MediaAssetType;
    content: string; // "Start: 02:10, End: 04:00" OR "Description of image..." OR Image URL
    prompt?: string; // AI prompt used to generate the image (if ai_generated_image)
    url?: string; // Generated image URL (populated after AI generation)
    status?: 'pending' | 'generated' | 'failed'; // Generation status
}

export interface LessonMetadata {
    title: string;
    target_audience: string;
    duration: string;
    subject?: string;
    learning_objectives?: string[]; // Added: Clear learning goals
}

export interface HookSection {
    script_for_teacher: string;
    media_asset?: MediaAsset;
    classroom_management_tip?: string; // Added: Tips for teacher (e.g., "If students are noisy, wait 10 seconds")
}

export interface DirectInstructionSlide {
    slide_title: string;
    bullet_points_for_board: string[];
    script_to_say: string;
    media_asset?: MediaAsset;
    timing_estimate?: string; // Added: e.g., "3-5 minutes"
    differentiation_note?: string; // Added: Tips for advanced/struggling students
}

export interface DirectInstructionSection {
    slides: DirectInstructionSlide[];
}

/**
 * Guided Practice - Pedagogical guidance for in-class practice
 * (המורה מנחה את התלמידים בכיתה)
 */
export interface GuidedPracticeSection {
    teacher_facilitation_script: string; // How to introduce and guide the practice
    suggested_activities: {
        activity_type: string; // e.g., "multiple-choice", "memory_game"
        description: string; // What this activity should assess
        facilitation_tip?: string; // How to guide students through it
    }[];
    differentiation_strategies?: {
        for_struggling_students: string;
        for_advanced_students: string;
    };
    assessment_tips?: string[]; // What to look for while students practice
}

/**
 * Independent Practice - Ready-to-use digital activities
 * (פעילויות דיגיטליות מוכנות לשליחה לתלמידים)
 */
export interface IndependentPracticeSection {
    introduction_text: string; // Brief instructions for students
    interactive_blocks: any[]; // Array of ActivityBlock (ready-to-use activities)
    estimated_duration?: string; // e.g., "10-15 דקות"
    shareable_link?: string; // Generated link to share with students
}

export interface DiscussionSection {
    questions: string[];
    facilitation_tips?: string[]; // Added: How to guide discussion
}

export interface SummarySection {
    takeaway_sentence: string;
    visual_summary?: MediaAsset; // Added: Optional visual summary/infographic
    homework_suggestion?: string; // Added: Optional follow-up activity
}

/**
 * The Master Teacher Lesson Plan Structure V4 (Enhanced)
 *
 * KEY IMPROVEMENTS:
 * - Auto-generated visuals (AI images, infographics)
 * - TWO types of practice sections:
 *   1. Guided Practice: Pedagogical guidance for in-class facilitation
 *   2. Independent Practice: Ready-to-use digital activities (shareable with students)
 * - Classroom management tips embedded
 * - Differentiation strategies included
 * - Rich metadata and learning objectives
 *
 * (Distinct from Student Activity / Quiz)
 */
export interface TeacherLessonPlan {
    lesson_metadata: LessonMetadata;
    hook: HookSection;
    direct_instruction: DirectInstructionSection;
    guided_practice: GuidedPracticeSection;
    independent_practice: IndependentPracticeSection;
    discussion: DiscussionSection;
    summary: SummarySection;
}

